# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
  
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'monitor-traffic-tcpdump'
  
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['10.5.0.1:8000'] # The Network Traffic Metrics IP/port

  - job_name: 'average-pools-latency'
  
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['pools-latency-calculator:1234'] # The Network Traffic Metrics IP/port

  - job_name: 'sv1-custom-proxy'
  
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['sv1-custom-proxy:2345'] # The Network Traffic Metrics IP/port

  - job_name: 'sv2-custom-proxy'
  
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['sv2-custom-proxy:3456'] # The Network Traffic Metrics IP/port
  
  - job_name: 'sv2-new-job-proxy'
    scrape_interval: 10s
    static_configs:
      - targets: ['sv2-new-job-proxy:3477']

  - job_name: 'sv2-pool-new-job-proxy'
    scrape_interval: 10s
    static_configs:
      - targets: ['sv2-pool-new-job-proxy:3497']